classmap_coco = {u'airplane': 5,
 u'apple': 53,
 u'backpack': 27,
 u'banana': 52,
 u'baseball bat': 39,
 u'baseball glove': 40,
 u'bear': 23,
 u'bed': 65,
 u'bench': 15,
 u'bicycle': 2,
 u'bird': 16,
 u'boat': 9,
 u'book': 84,
 u'bottle': 44,
 u'bowl': 51,
 u'broccoli': 56,
 u'bus': 6,
 u'cake': 61,
 u'car': 3,
 u'carrot': 57,
 u'cat': 17,
 u'cell phone': 77,
 u'chair': 62,
 u'clock': 85,
 u'couch': 63,
 u'cow': 21,
 u'cup': 47,
 u'dining table': 67,
 u'dog': 18,
 u'donut': 60,
 u'elephant': 22,
 u'fire hydrant': 11,
 u'fork': 48,
 u'frisbee': 34,
 u'giraffe': 25,
 u'hair drier': 89,
 u'handbag': 31,
 u'horse': 19,
 u'hot dog': 58,
 u'keyboard': 76,
 u'kite': 38,
 u'knife': 49,
 u'laptop': 73,
 u'microwave': 78,
 u'motorcycle': 4,
 u'mouse': 74,
 u'orange': 55,
 u'oven': 79,
 u'parking meter': 14,
 u'person': 1,
 u'pizza': 59,
 u'potted plant': 64,
 u'refrigerator': 82,
 u'remote': 75,
 u'sandwich': 54,
 u'scissors': 87,
 u'sheep': 20,
 u'sink': 81,
 u'skateboard': 41,
 u'skis': 35,
 u'snowboard': 36,
 u'spoon': 50,
 u'sports ball': 37,
 u'stop sign': 13,
 u'suitcase': 33,
 u'surfboard': 42,
 u'teddy bear': 88,
 u'tennis racket': 43,
 u'tie': 32,
 u'toaster': 80,
 u'toilet': 70,
 u'toothbrush': 90,
 u'traffic light': 10,
 u'train': 7,
 u'truck': 8,
 u'tv': 72,
 u'umbrella': 28,
 u'vase': 86,
 u'wine glass': 46,
 u'zebra': 24}

classmap_voc = [u'aeroplane', u'bicycle', u'bird', u'boat', u'bottle', u'bus', u'car', u'cat', u'chair', u'cow', u'diningtable', u'dog', u'horse', u'motorbike', u'person', u'pottedplant', u'sheep', u'sofa', u'train', u'tvmonitor']
